=== biramo/Proyecto-4-Web/xml/llar_online.dtd
<!ENTITY empresa "Llar Online">
<!ENTITY eco "fabricación sostenible">

<!ELEMENT llar_online (tienda?, productos)>
<!ATTLIST llar_online
    id_catalogo CDATA #REQUIRED
    idioma CDATA #REQUIRED
    version CDATA #REQUIRED
>

<!ELEMENT tienda (descripcion)>
<!ATTLIST tienda
    nombre CDATA #REQUIRED
    moneda CDATA #REQUIRED
    pais CDATA #REQUIRED
>

<!ELEMENT descripcion (#PCDATA)>

<!ELEMENT productos (producto+)>
<!ATTLIST productos
    total CDATA #REQUIRED
>

<!ELEMENT producto (marca, nombre_comercial, referencia, descripcion_corta, caracteristicas, precio, disponibilidad, tiempo_entrega, imagenes)>
<!ATTLIST producto
    id ID #REQUIRED
    tipo CDATA #REQUIRED
    destacado (si|no) #REQUIRED
>

<!ELEMENT marca (#PCDATA)>
<!ELEMENT nombre_comercial (#PCDATA)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT descripcion_corta (#PCDATA)>

<!ELEMENT caracteristicas (caracteristica+)>

<!ELEMENT caracteristica (#PCDATA)>
<!ATTLIST caracteristica
    nombre (material|color|alto|largo|ancho|categoria|forma|tipodecama|reposabrazos) #REQUIRED
    unidad CDATA #IMPLIED
>


<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio
    moneda CDATA #REQUIRED
>

<!ELEMENT disponibilidad (#PCDATA)>

<!ELEMENT tiempo_entrega (#PCDATA)>
<!ATTLIST tiempo_entrega
    unidad CDATA #REQUIRED
>

<!ELEMENT imagenes (imagen+)>

<!ELEMENT imagen (#PCDATA)>
<!ATTLIST imagen
    principal (si|no) #REQUIRED
>

=== biramo/Proyecto-4-Web/xml/llar_online_3_ficha.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="llar_online_3.xsl"?>
<!DOCTYPE llar_online SYSTEM "llar_online.dtd">

<llar_online id_catalogo="CAT-2026-01" idioma="es" version="1.0">
	<tienda nombre="&empresa;" moneda="EUR" pais="ES">
		<descripcion>Catálogo de productos para el hogar con foco en el diseño, la calidad y la &eco;.
	    </descripcion>
	</tienda>
	<productos>
		<producto id="PR001" tipo="cama" destacado="si">
			<marca>Nordic Home</marca>
		    <nombre_comercial>Cama Brisa Roble</nombre_comercial>
		    <referencia>DES-001</referencia>
		    <descripcion_corta>Cama de diseño sencillo para dormitorio principal.</descripcion_corta>
		    <caracteristicas>
				<caracteristica nombre="material">Madera de roble</caracteristica>
		        <caracteristica nombre="color">Natural</caracteristica>
		        <caracteristica nombre="alto" unidad="cm">110</caracteristica>
		        <caracteristica nombre="largo" unidad="cm">200</caracteristica>
		        <caracteristica nombre="ancho" unidad="cm">160</caracteristica>
		        <caracteristica nombre="categoria">Descanso</caracteristica>
				<caracteristica nombre="tipodecama">Matrimonial</caracteristica>
			</caracteristicas>
		    <precio moneda="EUR">499.99</precio>
		    <disponibilidad>Disponible</disponibilidad>
		    <tiempo_entrega unidad="dias">7</tiempo_entrega>
		    <imagenes>
				<imagen principal="si">img/productos/PR001_1.png</imagen>
		        <imagen principal="no">img/productos/PR001_2.png</imagen>
			</imagenes>
		</producto>
		
		<producto id="PR002" tipo="cabecero" destacado="no">
			<marca>EcoDream</marca>
		    <nombre_comercial>Cabecero Nube Beige</nombre_comercial>
		    <referencia>DES-002</referencia>
		    <descripcion_corta>Cabecero tapizado de estilo suave y moderno.</descripcion_corta>
		    <caracteristicas>
				<caracteristica nombre="material">Tela y madera</caracteristica>
		        <caracteristica nombre="color">Beige</caracteristica>
		        <caracteristica nombre="alto" unidad="cm">120</caracteristica>
		        <caracteristica nombre="largo" unidad="cm">8</caracteristica>
		        <caracteristica nombre="ancho" unidad="cm">165</caracteristica>
		        <caracteristica nombre="categoria">Descanso</caracteristica>
			</caracteristicas>
		    <precio moneda="EUR">189.95</precio>
		    <disponibilidad>Disponible</disponibilidad>
		    <tiempo_entrega unidad="dias">5</tiempo_entrega>
		    <imagenes>
				<imagen principal="si">img/productos/PR002_1.png</imagen>
		        <imagen principal="no">img/productos/PR002_2.png</imagen>
			</imagenes>
		</producto>
		
		<producto id="PR003" tipo="mesita" destacado="no">
			<marca>Casa Verde</marca>
		    <nombre_comercial>Mesita Alba Blanca</nombre_comercial>
		    <referencia>DES-003</referencia>
		    <descripcion_corta>Mesita auxiliar ideal para dormitorio o zona de descanso.</descripcion_corta>
		    <caracteristicas>
				<caracteristica nombre="material">Madera lacada</caracteristica>
		        <caracteristica nombre="color">Blanco</caracteristica>
		        <caracteristica nombre="alto" unidad="cm">55</caracteristica>
		        <caracteristica nombre="largo" unidad="cm">40</caracteristica>
		        <caracteristica nombre="ancho" unidad="cm">45</caracteristica>
		        <caracteristica nombre="categoria">Descanso</caracteristica>
				<caracteristica nombre="forma">Rectangular</caracteristica>
			</caracteristicas>
		    <precio moneda="EUR">79.90</precio>
		    <disponibilidad>Disponible</disponibilidad>
		    <tiempo_entrega unidad="dias">4</tiempo_entrega>
		    <imagenes>
				<imagen principal="si">img/productos/PR003_1.png</imagen>
		        <imagen principal="no">img/productos/PR003_2.png</imagen>
			</imagenes>
		</producto>
		
		<producto id="PR004" tipo="tumbona" destacado="si">
			<marca>Sun Garden</marca>
		    <nombre_comercial>Tumbona Arena Relax</nombre_comercial>
		    <referencia>EXT-001</referencia>
		    <descripcion_corta>Tumbona cómoda para jardín, terraza o piscina.</descripcion_corta>
		    <caracteristicas>
				<caracteristica nombre="material">Aluminio y textileno</caracteristica>
		        <caracteristica nombre="color">Gris</caracteristica>
		        <caracteristica nombre="alto" unidad="cm">35</caracteristica>
		        <caracteristica nombre="largo" unidad="cm">190</caracteristica>
		        <caracteristica nombre="ancho" unidad="cm">68</caracteristica>
		        <caracteristica nombre="categoria">Exterior</caracteristica>
				<caracteristica nombre="reposabrazos">No</caracteristica>
			</caracteristicas>
		    <precio moneda="EUR">159.00</precio>
		    <disponibilidad>Disponible</disponibilidad>
		    <tiempo_entrega unidad="dias">6</tiempo_entrega>
		    <imagenes>
				<imagen principal="si">img/productos/PR004_1.png</imagen>
		        <imagen principal="no">img/productos/PR004_2.png</imagen>
			</imagenes>
		</producto>
		
		<producto id="PR005" tipo="silla_exterior" destacado="no">
			<marca>Terra Natura</marca>
		    <nombre_comercial>Silla Patio Verde</nombre_comercial>
		    <referencia>EXT-002</referencia>
		    <descripcion_corta>Silla ligera para espacios exteriores y zonas de descanso al aire libre.</descripcion_corta>
		    <caracteristicas>
				<caracteristica nombre="material">Ratán sintético y acero</caracteristica>
		        <caracteristica nombre="color">Verde oliva</caracteristica>
		        <caracteristica nombre="alto" unidad="cm">84</caracteristica>
		        <caracteristica nombre="largo" unidad="cm">58</caracteristica>
		        <caracteristica nombre="ancho" unidad="cm">56</caracteristica>
		        <caracteristica nombre="categoria">Exterior</caracteristica>
				<caracteristica nombre="reposabrazos">No</caracteristica>
			</caracteristicas>
		    <precio moneda="EUR">69.50</precio>
		    <disponibilidad>Disponible</disponibilidad>
		    <tiempo_entrega unidad="dias">3</tiempo_entrega>
		    <imagenes>
				<imagen principal="si">img/productos/PR005_1.png</imagen>
		        <imagen principal="no">img/productos/PR005_2.png</imagen>
			</imagenes>
		</producto>
		
		<producto id="PR006" tipo="mesa_exterior" destacado="no">
			<marca>Outdoor Life</marca>
		    <nombre_comercial>Mesa Terraza Coral</nombre_comercial>
		    <referencia>EXT-003</referencia>
		    <descripcion_corta>Mesa resistente para comidas y reuniones en exterior.</descripcion_corta>
		    <caracteristicas>
				<caracteristica nombre="material">Madera de acacia</caracteristica>
		        <caracteristica nombre="color">Marron</caracteristica>
		        <caracteristica nombre="alto" unidad="cm">75</caracteristica>
		        <caracteristica nombre="largo" unidad="cm">150</caracteristica>
		        <caracteristica nombre="ancho" unidad="cm">90</caracteristica>
		        <caracteristica nombre="categoria">Exterior</caracteristica>
				<caracteristica nombre="forma">Rectangular</caracteristica>
			</caracteristicas>
		    <precio moneda="EUR">229.00</precio>
		    <disponibilidad>Pocas unidades</disponibilidad>
		    <tiempo_entrega unidad="dias">8</tiempo_entrega>
		    <imagenes>
				<imagen principal="si">img/productos/PR006_1.png</imagen>
		        <imagen principal="no">img/productos/PR006_2.png</imagen>
			</imagenes>
		</producto>
		
		<producto id="PR007" tipo="mesa_comedor" destacado="si">
			<marca>Nordic Home</marca>
		    <nombre_comercial>Mesa Comedor Sena</nombre_comercial>
		    <referencia>COM-001</referencia>
		    <descripcion_corta>Mesa amplia para comedor de estilo contemporáneo.</descripcion_corta>
		    <caracteristicas>
				<caracteristica nombre="material">Madera y metal</caracteristica>
		        <caracteristica nombre="color">Negro</caracteristica>
		        <caracteristica nombre="alto" unidad="cm">76</caracteristica>
		        <caracteristica nombre="largo" unidad="cm">180</caracteristica>
		        <caracteristica nombre="ancho" unidad="cm">95</caracteristica>
		        <caracteristica nombre="categoria">Comedor</caracteristica>
				<caracteristica nombre="forma">Rectangular</caracteristica>
			</caracteristicas>
		    <precio moneda="EUR">339.90</precio>
		    <disponibilidad>Disponible</disponibilidad>
		    <tiempo_entrega unidad="dias">6</tiempo_entrega>
		    <imagenes>
				<imagen principal="si">img/productos/PR007_1.png</imagen>
		        <imagen principal="no">img/productos/PR007_2.png</imagen>
			</imagenes>
		</producto>
		
		<producto id="PR008" tipo="silla_comedor" destacado="no">
			<marca>Linea Viva</marca>
		    <nombre_comercial>Silla Comedor Duna</nombre_comercial>
		    <referencia>COM-002</referencia>
		    <descripcion_corta>Silla elegante para comedor con respaldo ergonómico.</descripcion_corta>
		    <caracteristicas>
				<caracteristica nombre="material">Madera y poliester</caracteristica>
		        <caracteristica nombre="color">Azul petroleo</caracteristica>
		        <caracteristica nombre="alto" unidad="cm">88</caracteristica>
		        <caracteristica nombre="largo" unidad="cm">52</caracteristica>
		        <caracteristica nombre="ancho" unidad="cm">49</caracteristica>
		        <caracteristica nombre="categoria">Comedor</caracteristica>
				<caracteristica nombre="reposabrazos">No</caracteristica>
			</caracteristicas>
		    <precio moneda="EUR">94.95</precio>
		    <disponibilidad>Disponible</disponibilidad>
		    <tiempo_entrega unidad="dias">4</tiempo_entrega>
		    <imagenes>
				<imagen principal="si">img/productos/PR008_1.png</imagen>
		        <imagen principal="no">img/productos/PR008_2.png</imagen>
			</imagenes>
		</producto>
		
		<producto id="PR009" tipo="aparador" destacado="no">
			<marca>Casa Verde</marca>
		    <nombre_comercial>Aparador Nexo Roble</nombre_comercial>
		    <referencia>COM-003</referencia>
		    <descripcion_corta>Aparador funcional para guardar vajilla y objetos del comedor.</descripcion_corta>
		    <caracteristicas>
				<caracteristica nombre="material">Madera de roble</caracteristica>
